common: &common
  adapter: postgresql
  encoding: unicode
  min_messages: warning

development: &development
  <<: *common
  database: coffee_here_development

test: &test
  <<: *common
  database: coffee_here_test
